Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -22,9 +22,20 @@ jobs:
         env:
           DOMAIN1: ${{ secrets.DOMAIN1 }}
           DOMAIN2: ${{ secrets.DOMAIN2 }}
+          EMAIL: ${{ secrets.EMAIL }}  # 从 GitHub Secrets 中获取电子邮件
         run: |
-          # 请求新的 SSL 证书，每次都重新申请
-          sudo certbot certonly --standalone -d $DOMAIN1 -d $DOMAIN2 --agree-tos --non-interactive
+          # 打印 DOMAIN1 和 DOMAIN2 值进行调试
+          echo "DOMAIN1: $DOMAIN1"
+          echo "DOMAIN2: $DOMAIN2"
+          
+          # 确保域名变量不是空的
+          if [[ -z "$DOMAIN1" ]] || [[ -z "$DOMAIN2" ]]; then
+            echo "Error: DOMAIN1 or DOMAIN2 is empty"
+            exit 1
+          fi
+          
+          # 使用 sudo 提升权限来请求证书，并提供 --email 参数
+          sudo certbot certonly --standalone -d $DOMAIN1 -d $DOMAIN2 --agree-tos --email $EMAIL --non-interactive
 
       - name: Save SSL certificate details
         run: |
